# build the project
# check to change
tasks:
  - name: Setup maven
    init: mvn install
  - name: Setup Mysql  
    init: docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=Pass123$ -d mysql:5.7 && sudo apt install maven && docker exec -it some-mysql  mysql -uroot -pPass123$
  - name: Example of passing an environment variable to a command
    env:
      PRINT_ME: "GitpodID"
    command: echo "$PRINT_ME"         
ports:
  - port: 35729
    onOpen: ignore     

